name: Continous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore ./JellyfishBackend.sln 

    - name: Build
      run: dotnet build ./JellyfishBackend.sln --configuration Backend --no-restore

    - name: Test
      run: dotnet test ./JellyfishBackend.sln --configuration Backend --no-restore --no-build
